### ISSUE TITLE
Mal calculado el daño de los ataques del jugador

### ISSUE THREAD

**Issue by egalla02** [Proyectos1-FDI-UCM/c2021-Grupo09#6]
**Descripción**

En el plan de pruebas aparece especificado que los ataques del jugador deberían ser capaces de matar a los enemigos básicos de 2 disparos. No obstante, los enemigos básicos mueren tras 3 disparos del jugador.

**Pasos**

1. Iniciar una nueva partida
2. Esperar a que aparezcan los enemigos
3. Situar el ratón sobre uno de los enemigos y hacer click varias veces

**Vídeo** : [PlayerAttacks](https://www.youtube.com/watch?v=P8CK3BaBzhY)

**Comment by theligero** [comment]
El daño de las balas fue propuesto inicialmente para la alpha en dos. Más tarde nos dimos cuenta de que era excesivo y lo subimos a tres. Posiblemente se nos pasó cambiarlo en el plan de pruebas, pero a día de hoy no es tan relevante, pues con el balanceo que estamos llevando a cabo creo incluso recordar que lo hemos subido a cuatro o a cinco incluso.
